services:
  gitea:
    image: docker.gitea.com/gitea:1.25.5
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__security__INSTALL_LOCK=false
      - GITEA__server__DOMAIN=git.local
      - GITEA__server__ROOT_URL=http://git.local:3001/
      - GITEA__server__SSH_DOMAIN=git.local
      - GITEA__database__DB_TYPE=sqlite3
    ports:
      - "3001:3000"  # HTTP web UI
      - "2222:22"    # SSH git access
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
