---
- name: Apply common configuration to all hosts
  hosts: homelab
  become: true
  roles:
    - role: common

- name: Install Docker on docker hosts
  hosts: docker_hosts
  become: true
  roles:
    - role: docker_host

- name: Enable NVIDIA runtime on Plex
  hosts: plex-1
  become: true
  roles:
    - role: plex_gpu
