---
- name: Restart Docker
  ansible.builtin.service:
    name: docker
    state: restarted

- name: Reboot for NVIDIA driver
  ansible.builtin.reboot:
    reboot_timeout: 1200
  when: plex_gpu_reboot_after_driver
